export const MAP_GENERATION_PAGE_API_GENERATE_MAP = "/maps/generate";
export const MAP_GENERATION_PAGE_API_PUBLISH = "/maps/create";
export const MAP_GENERATION_PAGE_SEED_TYPING_DELAY = 1000; // 1 second
export const MAP_GENERATION_PAGE_PUBLISHED_REDIRECT_URL = "/";
export const MAP_GENERATION_PAGE_MAP_REDIRECT_URL = "/map"